version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  message-processor:
    build:
      context: .
      dockerfile: cmd/message-processor/Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
      - redis

  reporting-api:
    build:
      context: .
      dockerfile: cmd/reporting-api/Dockerfile
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      - redis
